
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: go-contactsdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=contactsdb
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: